### ISSUE TITLE
Document recommended filename extension and mime-type for Ion Schema

### ISSUE THREAD

**Issue by nematsakis** [amzn/ion-schema#121]
I cannot find documented anywhere on the [Ion Schema site](https://amazon-ion.github.io/ion-schema) the recommended filename extension and/or MIME type for Ion Schema files.  I believe the answer is that the specification does not require a filename extension, but `.isl` is the recommended extension. It would be helpful if the documentation had a FAQ that addressed these questions.

**Comment by popematt** [comment]
If you need a MIME type, you can use `application/ion`, which is listed in the [IANA Provisional Standard Media Types Registry](https://www.iana.org/assignments/provisional-standard-media-types/provisional-standard-media-types.xhtml)

The convention that we have used for the the filename extension is indeed `.isl`, but you are correct that no particular filename extension is required.

I'll leave this open until we update the Ion Schema documentation.
