### ISSUE TITLE
allow structs to be constrained such that all fields can appear at most once

### ISSUE THREAD

**Issue by pbcornell** [amzn/ion-schema#14]
The default `occurs` behavior for a specified field is `optional`; the default `occurs` behavior for an open-content (unspecified) field is not clear in the spec (#12), but the reference implementation allows an open-content field to occur any number of times.

Addressing these issues might take the form of:
1. allowing field defaults to be specified for a struct (see #13)
1. adding a `content_occurs` (or `open_content_occurs`?) constraint, configured in the same manner as the `occurs` constraint, but applicable to all open-content fields in a struct

**Comment by popematt** [comment]
Resolved by #76 as a consequence of #44 in Ion Schema 2.0.

It is now possible to model each field name to appear at most once like this:

```
$ion_schema_2_0

type::{
  name: foo,
  field_names: distinct::symbol,
}
```
