### ISSUE TITLE
Provide a way to require at least one annotation without specifying the exact annotation 

### ISSUE THREAD

**Issue by mwfpope** [amzn/ion-schema#23]
We have a use case where we would like to make sure that certain types do or do not have an annotation, but we don't always care what the annotation is. It would be helpful to have a way to indicate that at least one annotation is required, but without having to specify which annotation it is.

It would be sufficient just to add support for requiring an annotation. Then I believe that requiring no annotations could be derived like using the `not` constraint. (Note: I'm not trying to propose any particular syntax here—just trying to illustrate the negation.)

```
type::{
  name: has_at_least_one_annotation,
  annotations: required
}

type::{
  name: has_no_annotations,
  not: has_at_least_one_annotation 
}
```

**Comment by mwfpope** [comment]
I'm interested in implementing this feature, so I'd like to discuss this and get some alignment on a solution for this, if possible.
I've had a few ideas about how to introduce this feature into the spec.

__1. Use a symbol to indicate there should be no annotations.__

Eg. `annotations: none`

I think this is the simplest possible solution, and it's immediately obvious to the reader what this constrain means.

When I first opened this issue, I asked for a way to indicate "at least one annotation". After working through some examples, I think that being able to indicate "no annotations allowed" is a superior option.

Consider the following: `annotations: any`, `annotations: at_least_one`

This seems like it would be more confusing because `any` is already a type, and it's not immediately clear that an annotation is required. If we use `at_least_one`, then it's clear, but we're also starting to represent numbers as symbols, which is messy and seems like something to be avoided.

Requiring "at least one" annotation could still be expressed like this:
```
type:: {
  name: is_annotated,
  not: { annotations: none },
}
```

__2. Provide an annotation to indicate that annotation content is closed__

Eg.
```
annotations: closed::[red, blue, green] // matches iff the value's annotations are a subset of red, green, blue
annotations: closed::[] // matches iff the value has no annotations
```

This would support a wider variety of use cases than the first option. (Also, I've always wondered why there's no way to put an "upper" bound on the annotations.) Another possible plus for this approach is that it could help resolve part of [this issue](https://github.com/amzn/ion-schema-kotlin/issues/150) by making it clear when open content should be allowed for annotations. For example, it would enable use cases like this

```
type::{name: abc, type: symbol, annotations: closed::[required::a, b, c]}
-------------------------------------------------------------------------
         a::hello: true
      a::b::hello: true
      a::c::hello: true
   a::b::c::hello: true
      a::d::hello: false // not allowed to have open content
      b::c::hello: false // missing 'a'
```

__3. Add a new constraint type.__

Eg.
```
annotation_count: range::[1,max]
annotation_count: 0
```

This is easy to understand, and maybe it would be useful for _someone_ to allow, for example, specifically 3 to 7 annotations, but _I_ can't think of a use case for that. I would personally rule this out because I'm hesitant to introduce a new constraint type, and I don't think it adds as much value as option 2. When combined with [this issue](https://github.com/amzn/ion-schema-kotlin/issues/150)

----

I am preferential to options 1 (`annotations: none`) and 2 (`annotations: closed::[a, b, c]`) or even a combination of 1 and 2 where `annotations: none` is basically a synonym for `annotations: closed::[]`.

Do either of these options align with the design tenets for the ion schema language? Are there any refinements or alternative approaches that you would like to suggest?

**Comment by almann** [comment]
Thanks for your very detailed set of proposals here.

> I am preferential to options 1 (`annotations: none`) and 2 (`annotations: closed::[a, b, c]`) or even a combination of 1 and 2 where `annotations: none` is basically a synonym for `annotations: closed::[]`.
> 
> Do either of these options align with the design tenets for the ion schema language? Are there any refinements or alternative approaches that you would like to suggest?

I largely agree with your assessment here, specifically I am leaning towards option 2.  I don't think we need a synonym here for `none` (I think it might be questionable because I would think `none` is just a synonym for `[]` rather than `closed::[]`.

Please feel free to submit a PR against the spec with the intended change.  We will have to decide how we want to rev the specification version, but I can bring it up with some folks on the team about that separately.
