### ISSUE TITLE
Consider deprecating `content: closed`

### ISSUE THREAD

**Issue by popematt** [amzn/ion-schema#47]
**The Problem**

Content closed is not a constraint—it is a pseudo-constraint that modifies the `fields` constraint. As noted in https://github.com/amzn/ion-schema-kotlin/issues/27, the spec is inconsistent with regard to open/closed content. 

* `fields` is modified by `content: closed`
* `ordered_elements` is closed by default, so `content: closed` has no effect
* `contains` allows open content, but is not affected by `content: closed` (however, you can emulate closed content for `contains` by adding `element: { valid_values: [ ... ] }`)
* `element` does not make sense to be closed/open because any open state would mean that `element` does nothing at all

For example, given these types

```
type::{
  name: foo,
  type: struct,
  content: closed,
  element: int,
}

type::{
  name: bar,
  type: foo,
  fields: {
    a: int,
    b: string,
  }
}
```

It is not obvious that the `content: closed` of `foo` will not apply to `bar` even though the `element: int` of `foo` will apply to `bar`.

Another example:

```
type::{
  name: foo,
  type: struct,
  fields: {
    a: int,
    b: string,
  }
}

type::{
  name: bar,
  type: foo,
  fields: {
    c: int,
    d: string,
  },
  content: closed,
}
```
In this example, it is not obvious whether `content: closed` allows only the fields in `bar` or to the fields in `foo` as well.

**Proposed Solution**

The solution is to deprecate `content: closed`.

If the change is introduced in a new minor version of Ion Schema, we want to maintain backwards compatibility, so this deprecation would be to "discourage the use of (something, such as a software product) in favor of a newer or better alternative" ([source](https://www.merriam-webster.com/dictionary/deprecation)) rather than to withdraw support entirely. If the change is to be introduced in a new major version, we should hard deprecate it (remove it entirely).

The `content: closed` constraint should be replaced by a `closed::` annotation on the fields constraint. This makes it clear what exactly is closed and how the "closing" would be "inherited" between types, and it also matches the `closed::` annotation that is available for the `annotations` constraint.

For example:
```
type::{
  name: point2d,
  type: struct,
  fields: closed::{
    x: number,
    y: number,
  }
}
```

**Comment by popematt** [comment]
Resolved by #76 in Ion Schema 2.0

**Comment by didibus** [comment]
With the new content closed, is it possible to restrict the fields to the union of the derived type and it's inherited ones?

In your example:

```
type::{
  name: foo,
  type: struct,
  fields: {
    a: int,
    b: string,
  }
}

type::{
  name: bar,
  type: foo,
  fields: {
    c: int,
    d: string,
  },
  content: closed,
}
```

The behavior we want, and I think is most intuitive, is to say that maps of type `bar` cannot have additional fields then the ones defined in both `bar` and `foo`, meaning it would be:

```
closed:: {
    a: int,
    b: string,
    c: int,
    d: string,
}
```

But obviously, we don't want to have to copy/paste the fields of `foo` into `bar` to close on them, we still want an inheritance.

Is this supported by 1.0 spec? Or by the new 2.0 spec? Or is this still not possible?

**Comment by popematt** [comment]
Neither Ion Schema 1.0 nor Ion Schema 2.0 support an object-oriented style of inheritance, so it is not possible.

We have intentionally avoided OOP inheritance in Ion Schema because for most constraints, there is no unsurprising way to handle inheritance. For example:

```ion
type::{
  name: foo,
  container_length: range::[1, 6],
  ordered_elements: [
    symbol,
    { type: int, occurs: range::[0, max] },
  ]
}

type::{
  name: bar,
  type: foo,
  container_length: range::[5, 10],
  ordered_elements: [
    $symbol,
    { type: number, occurs: range::[0, max] },
  ]
}
```
In this example, if there was OOP-style inheritance, what would that mean for the `container_length` of `bar`? Would the first ordered element be nullable, as allowed by `bar` or non-null as specified by `foo`? Or perhaps the `ordered_elements` would be appended instead of being overlayed?

For `fields` in particular, there are some other challenges.
```
type::{
  name: foo,
  fields: closed::{
    a: int,
    b: string,
  }
}

type::{
  name: bar,
  fields: {
    a: number,
    c: string,
    d: int,
  }
}

type::{
  name: tricky_fields,
  one_of: [ foo, bar ],
  fields: closed::{
    e: timestamp,
  },
  not: { fields: { d: any } }
}
```
Should the `fields` in `tricky_fields` inherit from one or both of `foo` or `bar`? (What if it was `any_of` or `all_of`?) Should the `not` remove the `d` field from the inheritance? How does the `closed::` in `foo` affect the inheritance?

Regardless of how we answer those questions, we still would be left with a situation where `fields` uses OOP-style inheritance, and none of the other constraints do, which is also a surprising behavior.

That being said, I think there is value in having _some_ sort of ability to inherit fields, so I'm going to open an issue for it. Please feel free to chime in with any suggestion you may have.
