### ISSUE TITLE
Clarify `RANGE` constraint behavior for special float values

### ISSUE THREAD

**Issue by alancai98** [amzn/ion-schema#55]
Currently, a [number range](https://github.com/amzn/ion-schema/blob/8b9fb9a671/docs/spec.md#rangenumber) is specified as follows:

>RANGE&lt;NUMBER&gt;
A `number` range includes all values of any numeric type (i.e. `float`, `int`, and `decimal`) that fall within that range mathematically. When testing a value for inclusion, the range bounds and the value that is being tested will all be converted to
`decimal` values for the sake of comparison. `number` ranges do not include values of any other type.

Should special float values (i.e. `+inf`, `-inf`, `nan`) be allowed in number ranges? I would think that these values cannot be defined in a number range. Also they cannot be converted to `decimal` values when testing a value for inclusion.

**Comment by popematt** [comment]
This sounds like a good idea.

We should also clarify that number ranges bounds must also be finite (or the symbols `min` or `max`). Right now, the spec doesn't explicitly prohibit `+/-inf` or `nan` as a range bound, but allowing non-numeric values as range bounds doesn't make sense and is not supported in the current implementations.
