### ISSUE TITLE
Clarify whether element constraint applies to documents or not

### ISSUE THREAD

**Issue by nematsakis** [amzn/ion-schema#88]
In the [Ion Schema 1.0 Container Constraints](https://amzn.github.io/ion-schema/docs/isl-1-0/spec#container-constraints) document section it states "The following constraints are applicable for lists, S-expressions, structs, and documents." but the element constraint description states "Defines the type and/or constraints for all values within a homogeneous list, S-expression, or struct.".

It seems strange that element cannot be used to constrain a document. Is this indeed the case? If so, it seems weird but I would suggest updating the section text to read "_Unless otherwise noted, the following constraints are applicable...".   If `element` is valid for a document, then the other text should be updated.

**Comment by popematt** [comment]
You can use `element` to constrain a document. The `ion-schema-tests` suite has some tests cases for it [here](https://github.com/amzn/ion-schema-tests/blob/8fdc08b322a8d287c94fd247a43ebbf2a7fca4a2/constraints/element/int.isl), so any Ion Schema implementation should support it even though the spec is a little unclear.

**Comment by nematsakis** [comment]
I'd suggest making the following update to the spec to clarify:
```
<code><b>element:</b> <i>&lt;TYPE_REFERENCE&gt;</i></code><br/>

- Defines the type and/or constraints for all values within a homogeneous list, S-expression, or struct.
+ Defines the type and/or constraints for all values with a homogeneous container.

```

Container is to be understood from the preceding text to include lists, S-expressions, structs, and documents.
